# Generated by Django 4.1.2 on 2022-11-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_num',
            field=models.PositiveIntegerField(),
        ),
    ]
