# Generated by Django 4.1.2 on 2022-11-11 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_student_age'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'roll_num')},
        ),
    ]
